/**
 * Test script for PDF generation
 * Renders a sample HTML document to PDF and saves to ./tmp
 */
import { getPdfGenerator, closePdfGenerator } from './services/pdfGenerator';
import { LocalStorageClient } from './storage/LocalStorageClient';

const SAMPLE_HTML = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Outlook Weekly Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    h1 {
      color: #0078d4;
      border-bottom: 3px solid #0078d4;
      padding-bottom: 10px;
    }
    h2 {
      color: #323130;
      margin-top: 30px;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
    }
    .section {
      margin-bottom: 30px;
      padding: 20px;
      background: #f3f2f1;
      border-radius: 4px;
    }
    .stat {
      display: inline-block;
      margin-right: 20px;
      padding: 10px 15px;
      background: white;
      border-radius: 4px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .stat strong {
      color: #0078d4;
      font-size: 24px;
    }
    .email-item {
      padding: 10px;
      margin: 10px 0;
      background: white;
      border-left: 4px solid #0078d4;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📧 Outlook Weekly Report</h1>
    <p><strong>Week of December 16 - 22, 2025</strong></p>
    <p>Generated for: dev@example.com</p>
  </div>

  <div class="section">
    <h2>📊 Email Statistics</h2>
    <div class="stat">
      <div>Emails Received</div>
      <strong>127</strong>
    </div>
    <div class="stat">
      <div>Emails Sent</div>
      <strong>43</strong>
    </div>
    <div class="stat">
      <div>Response Time</div>
      <strong>2.3h</strong>
    </div>
  </div>

  <div class="section">
    <h2>📅 Calendar Highlights</h2>
    <div class="email-item">
      <strong>Team Standup</strong><br>
      Mon-Fri, 9:00 AM - 9:15 AM<br>
      <em>5 meetings this week</em>
    </div>
    <div class="email-item">
      <strong>Project Review</strong><br>
      Thursday, 2:00 PM - 3:00 PM<br>
      <em>With: Engineering Team</em>
    </div>
    <div class="email-item">
      <strong>1:1 with Manager</strong><br>
      Friday, 3:00 PM - 3:30 PM<br>
      <em>Weekly check-in</em>
    </div>
  </div>

  <div class="section">
    <h2>✉️ Top Conversations</h2>
    <div class="email-item">
      <strong>Re: Q1 Planning</strong><br>
      From: Alice Johnson<br>
      <em>12 messages • Last reply: Dec 22, 4:30 PM</em>
    </div>
    <div class="email-item">
      <strong>Feature Request: Dark Mode</strong><br>
      From: Bob Smith<br>
      <em>8 messages • Last reply: Dec 21, 2:15 PM</em>
    </div>
    <div class="email-item">
      <strong>Weekly Newsletter</strong><br>
      From: Company Communications<br>
      <em>Opened Dec 20, 10:00 AM</em>
    </div>
  </div>

  <div class="footer">
    <p>Generated by Outlook Weekly Reports</p>
    <p>This is an automated report based on your Outlook activity</p>
  </div>
</body>
</html>
`;

async function testPdfGeneration() {
  console.log('='.repeat(60));
  console.log('PDF Generation Test');
  console.log('='.repeat(60));
  console.log('');

  try {
    // Initialize PDF generator
    console.log('[1/4] Initializing PDF generator...');
    const pdfGenerator = getPdfGenerator();

    // Generate PDF from HTML
    console.log('[2/4] Generating PDF from sample HTML...');
    const pdfBuffer = await pdfGenerator.generatePdf(SAMPLE_HTML, {
      format: 'Letter',
      printBackground: true,
    });
    console.log(`✅ PDF generated (${pdfBuffer.length} bytes)`);

    // Initialize storage client
    console.log('[3/4] Storing PDF to local filesystem...');
    const storageClient = new LocalStorageClient('./tmp');
    const timestamp = Date.now();
    const fileName = `test-report-${timestamp}.pdf`;
    const filePath = await storageClient.storePdf(fileName, pdfBuffer);
    console.log(`✅ PDF stored at: ${filePath}`);

    // Verify file exists
    console.log('[4/4] Verifying stored file...');
    const exists = await storageClient.exists(fileName);
    if (exists) {
      const publicUrl = await storageClient.getPublicUrl(fileName);
      console.log(`✅ File verified`);
      console.log(`📄 Access URL: ${publicUrl}`);
    } else {
      console.log('❌ File not found after storage');
    }

    console.log('');
    console.log('='.repeat(60));
    console.log('✅ PDF Generation Test Complete');
    console.log('='.repeat(60));
    console.log('');
    console.log(`File location: ${filePath}`);
    console.log(`Open the file to view the generated PDF`);

  } catch (error) {
    console.error('');
    console.error('='.repeat(60));
    console.error('❌ Test Failed');
    console.error('='.repeat(60));
    console.error(error);
    process.exit(1);
  } finally {
    // Cleanup browser
    await closePdfGenerator();
  }
}

// Run the test
testPdfGeneration();
